trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  ci: true  
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactsDir: '$(Build.ArtifactStagingDirectory)'

steps:
- task: UseDotNet@2
  displayName: "Install NET SDK from global.json"
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: "build"
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: "test"
  inputs:
    command: 'test'
    projects: 'test/**/*.csproj'
    arguments: '--no-build'

- task: DotNetCoreCLI@2
  displayName: "pack"
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    arguments: '-c $(BuildConfiguration)'
    nobuild: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'